import type { User, Hospital, Ambulance, EmergencyRequest, TriageRule, DashboardStats, BedInfo } from '@/types';

// ============================================================
// MOCK DATA - LifeLink Demo
// ============================================================

export const DEMO_PATIENTS: User[] = [
  {
    id: 'usr-patient-1',
    name: 'Arjun Mehta',
    email: 'patient@lifelink.com',
    phone: '+91-9876543210',
    role: 'PATIENT',
    bloodGroup: 'B_POS',
    dateOfBirth: '1992-03-15',
    gender: 'Male',
    address: '42, Hauz Khas, New Delhi - 110016',
    isVerified: true,
    allergies: ['Penicillin', 'Sulfa Drugs'],
    currentMedications: ['Metformin 500mg', 'Lisinopril 10mg'],
    chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
    emergencyContacts: [
      { id: 'ec-1', userId: 'usr-patient-1', name: 'Priya Mehta', relationship: 'Spouse', phone: '+91-9876543211' },
      { id: 'ec-2', userId: 'usr-patient-1', name: 'Raj Mehta', relationship: 'Father', phone: '+91-9876543212' },
    ],
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'usr-patient-2',
    name: 'Sneha Reddy',
    email: 'sneha@example.com',
    phone: '+91-9876543220',
    role: 'PATIENT',
    bloodGroup: 'O_NEG',
    dateOfBirth: '1988-07-22',
    gender: 'Female',
    address: '15, Jubilee Hills, Hyderabad - 500033',
    isVerified: true,
    allergies: ['Aspirin', 'Ibuprofen'],
    currentMedications: ['Levothyroxine 75mcg'],
    chronicConditions: ['Hypothyroidism'],
    emergencyContacts: [
      { id: 'ec-3', userId: 'usr-patient-2', name: 'Vikram Reddy', relationship: 'Spouse', phone: '+91-9876543221' },
    ],
    createdAt: '2024-02-20T14:00:00Z',
  },
  {
    id: 'usr-patient-3',
    name: 'Amit Patel',
    email: 'amit@example.com',
    phone: '+91-9876543230',
    role: 'PATIENT',
    bloodGroup: 'A_POS',
    dateOfBirth: '1995-11-08',
    gender: 'Male',
    address: '7, CG Road, Ahmedabad - 380006',
    isVerified: true,
    allergies: [],
    currentMedications: [],
    chronicConditions: [],
    emergencyContacts: [
      { id: 'ec-4', userId: 'usr-patient-3', name: 'Neha Patel', relationship: 'Sister', phone: '+91-9876543231' },
    ],
    createdAt: '2024-03-10T09:00:00Z',
  },
];

export const DEMO_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'Apollo Hospitals',
    address: '21, Greams Lane, Off Greams Road',
    city: 'Chennai',
    latitude: 13.0604,
    longitude: 80.2496,
    phone: '+91-44-28290600',
    email: 'info@apollohospitals.com',
    totalBeds: 550,
    availableBeds: 87,
    icuTotal: 60,
    icuAvailable: 12,
    emergencyRating: 4.8,
    isActive: true,
    specializations: ['Cardiology', 'Neurology', 'Trauma', 'Oncology'],
  },
  {
    id: 'hosp-2',
    name: 'Fortis Memorial Research Institute',
    address: 'Sector 44, Opposite HUDA City Centre',
    city: 'Gurugram',
    latitude: 28.4595,
    longitude: 77.0266,
    phone: '+91-124-4962200',
    email: 'info@fortishealthcare.com',
    totalBeds: 310,
    availableBeds: 43,
    icuTotal: 45,
    icuAvailable: 7,
    emergencyRating: 4.6,
    isActive: true,
    specializations: ['Cardiac Surgery', 'Orthopedics', 'Neurosurgery'],
  },
  {
    id: 'hosp-3',
    name: 'AIIMS New Delhi',
    address: 'Ansari Nagar East, New Delhi',
    city: 'New Delhi',
    latitude: 28.5672,
    longitude: 77.21,
    phone: '+91-11-26588500',
    email: 'info@aiims.edu',
    totalBeds: 2478,
    availableBeds: 312,
    icuTotal: 200,
    icuAvailable: 31,
    emergencyRating: 4.9,
    isActive: true,
    specializations: ['All Specialties', 'Research', 'Trauma', 'Burns'],
  },
  {
    id: 'hosp-4',
    name: 'Kokilaben Dhirubhai Ambani Hospital',
    address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows',
    city: 'Mumbai',
    latitude: 19.1364,
    longitude: 72.8296,
    phone: '+91-22-30999999',
    email: 'info@kokilabenhospital.com',
    totalBeds: 750,
    availableBeds: 124,
    icuTotal: 80,
    icuAvailable: 15,
    emergencyRating: 4.7,
    isActive: true,
    specializations: ['Cardiology', 'Orthopedics', 'Neuroscience', 'Organ Transplant'],
  },
  {
    id: 'hosp-5',
    name: 'Manipal Hospital',
    address: '98, HAL Old Airport Road',
    city: 'Bangalore',
    latitude: 12.9614,
    longitude: 77.6406,
    phone: '+91-80-25024444',
    email: 'info@manipalhospitals.com',
    totalBeds: 600,
    availableBeds: 95,
    icuTotal: 70,
    icuAvailable: 18,
    emergencyRating: 4.5,
    isActive: true,
    specializations: ['Oncology', 'Nephrology', 'Urology', 'Gastroenterology'],
  },
  {
    id: 'hosp-6',
    name: 'Medanta - The Medicity',
    address: 'Sector 38, Near Golf Course Road',
    city: 'Gurugram',
    latitude: 28.4636,
    longitude: 77.0493,
    phone: '+91-124-4141414',
    email: 'info@medanta.org',
    totalBeds: 1250,
    availableBeds: 178,
    icuTotal: 150,
    icuAvailable: 23,
    emergencyRating: 4.7,
    isActive: true,
    specializations: ['Heart Institute', 'Kidney & Urology', 'Neuroscience', 'Cancer Institute'],
  },
  {
    id: 'hosp-7',
    name: 'Christian Medical College',
    address: 'Ida Scudder Road, Vellore',
    city: 'Vellore',
    latitude: 12.9289,
    longitude: 79.1316,
    phone: '+91-416-2281000',
    email: 'info@cmcvellore.ac.in',
    totalBeds: 2700,
    availableBeds: 405,
    icuTotal: 180,
    icuAvailable: 34,
    emergencyRating: 4.8,
    isActive: true,
    specializations: ['Hematology', 'Pediatrics', 'Ophthalmology', 'Rehabilitation'],
  },
  {
    id: 'hosp-8',
    name: 'Tata Memorial Hospital',
    address: 'Dr. E Borges Marg, Parel',
    city: 'Mumbai',
    latitude: 18.9966,
    longitude: 72.8311,
    phone: '+91-22-24177000',
    email: 'info@tmc.gov.in',
    totalBeds: 1800,
    availableBeds: 230,
    icuTotal: 120,
    icuAvailable: 19,
    emergencyRating: 4.9,
    isActive: true,
    specializations: ['Cancer Care', 'Radiation Therapy', 'Surgical Oncology', 'Palliative Care'],
  },
];

export const DEMO_AMBULANCES: Ambulance[] = [
  { id: 'amb-1', vehicleNumber: 'DL-01-EM-0012', driverName: 'Rajesh Kumar', driverPhone: '+91-9876543101', status: 'AVAILABLE', currentLatitude: 28.6139, currentLongitude: 77.209 },
  { id: 'amb-2', vehicleNumber: 'MH-02-EM-3341', driverName: 'Priya Sharma', driverPhone: '+91-9876543102', status: 'EN_ROUTE', currentLatitude: 19.076, currentLongitude: 72.8777 },
  { id: 'amb-3', vehicleNumber: 'KA-05-EM-0087', driverName: 'Vikram Singh', driverPhone: '+91-9876543103', status: 'AVAILABLE', currentLatitude: 12.9716, currentLongitude: 77.5946 },
  { id: 'amb-4', vehicleNumber: 'TN-01-EM-2210', driverName: 'Suresh Babu', driverPhone: '+91-9876543104', status: 'BUSY', currentLatitude: 13.0827, currentLongitude: 80.2707 },
  { id: 'amb-5', vehicleNumber: 'HR-26-EM-5543', driverName: 'Ankit Verma', driverPhone: '+91-9876543105', status: 'AVAILABLE', currentLatitude: 28.4595, currentLongitude: 77.0266 },
  { id: 'amb-6', vehicleNumber: 'DL-01-EM-0078', driverName: 'Deepak Yadav', driverPhone: '+91-9876543106', status: 'EN_ROUTE', currentLatitude: 28.628, currentLongitude: 77.218 },
  { id: 'amb-7', vehicleNumber: 'WB-01-EM-1199', driverName: 'Arup Das', driverPhone: '+91-9876543107', status: 'OFFLINE', currentLatitude: 22.5726, currentLongitude: 88.3639 },
  { id: 'amb-8', vehicleNumber: 'GJ-01-EM-4456', driverName: 'Mehul Shah', driverPhone: '+91-9876543108', status: 'AVAILABLE', currentLatitude: 23.0225, currentLongitude: 72.5714 },
  { id: 'amb-9', vehicleNumber: 'DL-01-EM-0901', driverName: 'Rahul Joshi', driverPhone: '+91-9876543109', status: 'RETURNING', currentLatitude: 28.63, currentLongitude: 77.22 },
  { id: 'amb-10', vehicleNumber: 'TN-09-EM-6678', driverName: 'Karthik Rajan', driverPhone: '+91-9876543110', status: 'AVAILABLE', currentLatitude: 13.0827, currentLongitude: 80.2707 },
];

export const DEMO_EMERGENCIES: EmergencyRequest[] = [
  {
    id: 'ER-A3F2K1',
    patientId: 'usr-patient-1',
    ambulanceId: 'amb-1',
    hospitalId: 'hosp-3',
    status: 'EN_ROUTE',
    severity: 4,
    description: 'Chest pain and difficulty breathing',
    patientLatitude: 28.635,
    patientLongitude: 77.229,
    timeline: [
      { id: '1', event: 'SOS Triggered', timestamp: '2024-12-15T14:30:00Z' },
      { id: '2', event: 'Ambulance Assigned', description: 'DL-01-EM-0012 dispatched', timestamp: '2024-12-15T14:30:45Z' },
      { id: '3', event: 'En Route', description: 'Ambulance heading to patient location', timestamp: '2024-12-15T14:31:20Z' },
    ],
    createdAt: '2024-12-15T14:30:00Z',
    updatedAt: '2024-12-15T14:31:20Z',
  },
  {
    id: 'ER-B7G4M2',
    patientId: 'usr-patient-2',
    ambulanceId: 'amb-2',
    hospitalId: 'hosp-4',
    status: 'AMBULANCE_ASSIGNED',
    severity: 3,
    description: 'Severe allergic reaction',
    patientLatitude: 19.1364,
    patientLongitude: 72.8296,
    timeline: [
      { id: '1', event: 'SOS Triggered', timestamp: '2024-12-15T15:10:00Z' },
      { id: '2', event: 'Ambulance Assigned', description: 'MH-02-EM-3341 dispatched', timestamp: '2024-12-15T15:10:38Z' },
    ],
    createdAt: '2024-12-15T15:10:00Z',
    updatedAt: '2024-12-15T15:10:38Z',
  },
  {
    id: 'ER-C1H8N5',
    patientId: 'usr-patient-3',
    ambulanceId: 'amb-6',
    hospitalId: 'hosp-2',
    status: 'ARRIVED',
    severity: 5,
    description: 'Road traffic accident - possible spinal injury',
    patientLatitude: 28.628,
    patientLongitude: 77.218,
    timeline: [
      { id: '1', event: 'SOS Triggered', timestamp: '2024-12-15T13:45:00Z' },
      { id: '2', event: 'Ambulance Assigned', description: 'DL-01-EM-0078 dispatched', timestamp: '2024-12-15T13:45:30Z' },
      { id: '3', event: 'En Route', timestamp: '2024-12-15T13:46:10Z' },
      { id: '4', event: 'Arrived', description: 'Ambulance has arrived at the scene', timestamp: '2024-12-15T13:52:00Z' },
    ],
    createdAt: '2024-12-15T13:45:00Z',
    updatedAt: '2024-12-15T13:52:00Z',
  },
  {
    id: 'ER-D2J9P3',
    patientId: 'usr-patient-1',
    status: 'COMPLETED',
    severity: 2,
    description: 'Mild fever and dehydration',
    patientLatitude: 28.6139,
    patientLongitude: 77.209,
    timeline: [
      { id: '1', event: 'SOS Triggered', timestamp: '2024-09-20T10:00:00Z' },
      { id: '2', event: 'Admitted', description: 'Admitted to Fortis Memorial', timestamp: '2024-09-20T10:45:00Z' },
      { id: '3', event: 'Completed', description: 'Patient discharged', timestamp: '2024-09-20T18:00:00Z' },
    ],
    createdAt: '2024-09-20T10:00:00Z',
    updatedAt: '2024-09-20T18:00:00Z',
  },
];

// Mock users for all roles
export const MOCK_USERS: User[] = [
  ...DEMO_PATIENTS,
  {
    id: 'usr-driver-1',
    name: 'Rajesh Kumar',
    email: 'driver@lifelink.com',
    phone: '+91-9876543101',
    role: 'DRIVER',
    bloodGroup: 'A_POS',
    dateOfBirth: '1985-06-12',
    gender: 'Male',
    address: '15, Dwarka Sector 12, New Delhi',
    isVerified: true,
    allergies: [],
    currentMedications: [],
    chronicConditions: [],
    emergencyContacts: [],
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'usr-hospital-1',
    name: 'Dr. Ananya Gupta',
    email: 'hospital@lifelink.com',
    phone: '+91-9876543201',
    role: 'HOSPITAL_STAFF',
    bloodGroup: 'O_POS',
    dateOfBirth: '1980-01-25',
    gender: 'Female',
    address: 'AIIMS New Delhi, Ansari Nagar East',
    isVerified: true,
    allergies: [],
    currentMedications: [],
    chronicConditions: [],
    emergencyContacts: [],
    createdAt: '2024-01-05T08:00:00Z',
  },
  {
    id: 'usr-admin-1',
    name: 'Admin User',
    email: 'admin@lifelink.com',
    phone: '+91-9876543301',
    role: 'ADMIN',
    isVerified: true,
    allergies: [],
    currentMedications: [],
    chronicConditions: [],
    emergencyContacts: [],
    createdAt: '2024-01-01T00:00:00Z',
  },
];

// Ambulance waypoints for tracking simulation (Delhi area)
export const AMBULANCE_ROUTES: Record<string, { lat: number; lng: number }[]> = {
  'amb-1': [
    { lat: 28.6139, lng: 77.209 },
    { lat: 28.6165, lng: 77.2125 },
    { lat: 28.6202, lng: 77.2158 },
    { lat: 28.6245, lng: 77.2190 },
    { lat: 28.6283, lng: 77.2220 },
    { lat: 28.6310, lng: 77.2245 },
    { lat: 28.6335, lng: 77.2270 },
    { lat: 28.6350, lng: 77.2290 },
  ],
  'amb-6': [
    { lat: 28.628, lng: 77.218 },
    { lat: 28.6260, lng: 77.2160 },
    { lat: 28.6240, lng: 77.2140 },
    { lat: 28.6220, lng: 77.2125 },
    { lat: 28.6200, lng: 77.2115 },
    { lat: 28.6180, lng: 77.2110 },
    { lat: 28.6160, lng: 77.2110 },
    { lat: 28.6140, lng: 77.2110 },
  ],
};

// AI Triage rules
export const TRIAGE_RULES: TriageRule[] = [
  { keywords: ['chest pain', 'heart attack', 'cardiac', 'chest tightness'], severity: 5, conditions: ['Myocardial Infarction', 'Angina'], actions: ['Do not move the patient', 'Keep them calm', 'Loosen tight clothing', 'Chew aspirin if not allergic'] },
  { keywords: ['not breathing', 'unconscious', 'unresponsive', 'no pulse'], severity: 5, conditions: ['Cardiac Arrest'], actions: ['Start CPR immediately', 'Call emergency services', 'Use AED if available', 'Do not stop CPR until help arrives'] },
  { keywords: ['stroke', 'face drooping', 'slurred speech', 'arm weakness'], severity: 5, conditions: ['Stroke (CVA)'], actions: ['Note the time symptoms started', 'Keep patient comfortable', 'Do not give food or water', 'Keep airway clear'] },
  { keywords: ['severe bleeding', 'hemorrhage', 'blood loss'], severity: 5, conditions: ['Hemorrhagic Shock'], actions: ['Apply firm direct pressure', 'Elevate the wound if possible', 'Do not remove embedded objects', 'Keep patient warm'] },
  { keywords: ['head injury', 'concussion', 'skull fracture', 'head trauma'], severity: 4, conditions: ['Traumatic Brain Injury', 'Concussion'], actions: ['Immobilize the neck', 'Do not remove helmet', 'Monitor consciousness level', 'Apply ice wrapped in cloth'] },
  { keywords: ['broken bone', 'fracture', 'broken leg', 'broken arm'], severity: 3, conditions: ['Fracture'], actions: ['Immobilize the affected area', 'Do not try to realign', 'Apply ice to reduce swelling', 'Elevate if possible'] },
  { keywords: ['burn', 'burns', 'scald'], severity: 3, conditions: ['Burn Injury'], actions: ['Cool with running water for 20 min', 'Do not apply ice directly', 'Cover with sterile dressing', 'Do not burst blisters'] },
  { keywords: ['allergic reaction', 'swelling', 'hives', 'anaphylaxis', 'throat closing'], severity: 4, conditions: ['Anaphylaxis'], actions: ['Use epinephrine auto-injector if available', 'Keep patient calm', 'Loosen tight clothing', 'Monitor breathing'] },
  { keywords: ['seizure', 'epilepsy', 'convulsion'], severity: 4, conditions: ['Seizure/Epilepsy'], actions: ['Clear surrounding area', 'Do not restrain the person', 'Place on side to keep airway clear', 'Time the seizure'] },
  { keywords: ['difficulty breathing', 'shortness of breath', 'asthma', 'wheezing'], severity: 4, conditions: ['Respiratory Distress', 'Asthma Attack'], actions: ['Help them sit upright', 'Use inhaler if prescribed', 'Loosen clothing', 'Stay calm'] },
  { keywords: ['poison', 'overdose', 'ingested', 'swallowed'], severity: 4, conditions: ['Poisoning/Overdose'], actions: ['Do not induce vomiting', 'Save any remaining substance', 'Note time of ingestion', 'Keep patient conscious'] },
  { keywords: ['drowning', 'near drowning', 'water'], severity: 5, conditions: ['Drowning'], actions: ['Begin CPR if not breathing', 'Remove wet clothing', 'Keep warm', 'Do not use abdominal thrusts'] },
  { keywords: ['fever', 'high temperature', 'hot'], severity: 2, conditions: ['Fever', 'Infection'], actions: ['Rest and hydrate', 'Take paracetamol', 'Use cool compress', 'Monitor temperature'] },
  { keywords: ['stomach pain', 'abdominal pain', 'cramps'], severity: 2, conditions: ['Abdominal Pain'], actions: ['Rest in comfortable position', 'Do not eat solid food', 'Stay hydrated', 'Monitor symptoms'] },
  { keywords: ['diabetic', 'low blood sugar', 'hypoglycemia', 'insulin'], severity: 3, conditions: ['Hypoglycemia'], actions: ['Give sugar or sweet drink', 'Wait 15 minutes and recheck', 'Repeat if needed', 'Do not give insulin'] },
];

export const SEVERITY_LABELS: Record<number, { label: string; color: string; bgColor: string }> = {
  1: { label: 'LOW', color: 'text-green-700 dark:text-green-400', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  2: { label: 'MODERATE', color: 'text-yellow-700 dark:text-yellow-400', bgColor: 'bg-yellow-100 dark:bg-yellow-900/30' },
  3: { label: 'SERIOUS', color: 'text-orange-700 dark:text-orange-400', bgColor: 'bg-orange-100 dark:bg-orange-900/30' },
  4: { label: 'CRITICAL', color: 'text-red-700 dark:text-red-400', bgColor: 'bg-red-100 dark:bg-red-900/30' },
  5: { label: 'EXTREME', color: 'text-red-900 dark:text-red-300', bgColor: 'bg-red-200 dark:bg-red-900/50' },
};

export const DASHBOARD_STATS: DashboardStats = {
  activeEmergencies: 47,
  hospitalsOnline: 218,
  avgResponseTime: 3.8,
  patientSatisfaction: 4.9,
  totalLivesSaved: 52487,
  ambulancesOnline: 156,
};

// Simple seeded pseudo-random for deterministic hydration
function seededRandom(seed: number) {
  const x = Math.sin(seed * 9301 + 49297) * 233280;
  return x - Math.floor(x / 2147483648) * 2147483648;
}

// Mock beds for hospital dashboard
export const MOCK_BEDS: BedInfo[] = Array.from({ length: 40 }, (_, i) => ({
  id: `bed-${i + 1}`,
  number: `${Math.floor(i / 10) + 1}${String((i % 10) + 1).padStart(2, '0')}`,
  type: i < 10 ? 'ICU' : i < 20 ? 'EMERGENCY' : i < 30 ? 'GENERAL' : 'PEDIATRIC',
  status: seededRandom(i) > 0.4 ? 'OCCUPIED' : seededRandom(i + 100) > 0.5 ? 'AVAILABLE' : 'RESERVED',
  patientName: seededRandom(i + 200) > 0.4 ? ['R.K. Male, 45', 'S.P. Female, 32', 'A.M. Male, 28', 'P.R. Female, 67', 'V.S. Male, 54'][i % 5] : undefined,
}));

// Pre-set symptom chips for triage
export const SYMPTOM_CHIPS = [
  'Chest Pain',
  'Not Breathing',
  'Head Injury',
  'Severe Bleeding',
  'Unconscious',
  'Stroke Symptoms',
  'Allergic Reaction',
  'Seizure',
  'Difficulty Breathing',
  'Broken Bone',
  'Burn Injury',
  'High Fever',
];
